== Installing Forge

Installing Forge is a relatively short process, and this guide will take you through the fundamentals (providing links to external materials if required) however, if you encounter any issues with this process, please ask in the Forge Users mailing list, or if you think something is wrong with this guide, report a defect to the team.

=== Install a Forge Distribution

Follow these steps to install a Forge distribution:

*1. Ensure that you have already installed http://www.oracle.com/technetwork/java/javase/downloads/index.html[a Java 7+ JDK].*

*2. https://repository.jboss.org/nexus/service/local/artifact/maven/redirect?r=releases&amp;g=org.jboss.forge&amp;a=forge-distribution&amp;v=LATEST&amp;e=zip&amp;c=offline[Download] and Un-zip Forge into a folder on your hard-disk, this folder will be your `FORGE_HOME`*

*3. Add `$FORGE_HOME/bin` to your path (http://www.google.com/search?q=windows+edit+path[windows], http://www.google.com/search?q=linux+set+path[linux], http://www.google.com/search?q=mac+osx+edit+path[mac osx])*

On Unix based operating systems, this typically means editing your `~/.bashrc` or `~/.profile`; you will need to the following entries:

[source]
----
export FORGE_HOME=~/forge/
export PATH=$PATH:$FORGE_HOME/bin
----

While on Windows, you will need to right-click on open the "Control Panel", then click "System Properties", open the "Advanced" tab, then click "Environment Variables" and add these two entries visually. It is recommended to set User variables for Forge, unless you have placed the unzipped distribution in a folder where all users can access it.

****
You may also simply create a shortcut to `bin/forge` (Unix,) or `bin\forge.bat` (Windows,) and place it on your Desktop.
****

*4. Consider installing http://git-scm.com/[Git] and http://maven.apache.org/[Maven 3.1+] (both optional)*

*5. Open a command prompt and run `forge` (if you are on Windows, you will need to run `forge.bat` unless using a Unix-style terminal)*

[source]
----
localhost:~ $ forge
[~] $
----

=== That's it! You've got Forge installed, but what to do next?

You can start by Forging your first Java EE webapp in about five minutes, and there are a few things you should probably check-out. If you are confused at any time, try pressing *TAB*. For instance, if you have not yet seen the Forge built-in commands, you may either press TAB to see a list of the currently available commands, or get a more descriptive list by typing:

[source]
----
$ command-list
----

You may also use the `man` command for more detailed information about available Forge, a plugin, or a command.

[source]
----
$ man {command-name}
----
