== Forge 2.7.0.Final (Stoked) is here!

After almost two months of hard work, the Forge team is proud to inform that Forge 2.7.0.Final is now available, and with a new website!

What's new? 
============

We have fixed over 43 issues for this release. This makes it the best release ever launched.

* Website: Yes, we have a new website with brand new content and targeted at Forge 2, with some bits of documentation supplied by Antonio Goncalves (Thanks!). 
We're working hard on it and since we never stop innovating, there should be some design changes in the near future, so stay tuned!
* JBoss Tools 4.2.0.Beta3: We are now included in JBoss Tools 4.2.0.Beta3, which means that if you use JBoss Developer Studio, you'll already have JBoss Forge 2.7.0.Final installed. 
Just hit Ctrl+4 (or Cmd + 4 if you're on MacOSX) and you're ready to go! 


Release Notes - Forge - Version 2.7.0.Final
============================================
** Bug
    * [FORGE-1787] - When scaffolding with --webRoot parameter, pageTemplate.xhtml and search.xhtml are not right
    * [FORGE-1888] - REST resource generation is aborted instead of gracefully failing for unsupported features.
    * [FORGE-1891] - NPE while running Generate Entities from Tables command
    * [FORGE-1898] - Dashes in the project name makes jpa-new-entity execution to fail
    * [FORGE-1902] - Initial context in Forge Console appears to be incorrect
    * [FORGE-1903] - Stale values are displayed in the property dropdown for the "Constraint: Add" command in Forge
    * [FORGE-1904] - ConverterFactory can't handle primitive type conversion
    * [FORGE-1910] - CLAC doesn't properly calculate calling classloader or strip CLACs from compatible results
    * [FORGE-1912] - Embedded maven execution does not use the user settings file set as a system property
    * [FORGE-1914] - Generated DTOs and REST resources contain compiler errors when underlying JPA entities have primitive Ids


** Component  Upgrade
    * [FORGE-1832] - Upgrade to Roaster 2.5.0.Final
    * [FORGE-1857] - Upgrade to Aesh 0.55
    * [FORGE-1865] - Upgrade to Roaster 2.5.1.Final
    * [FORGE-1885] - Upgrade to Aesh 0.56
    * [FORGE-1889] - Upgrade to Roaster 2.6.0.Final



** Enhancement
    * [FORGE-885] - Support Bean Validation 1.1 method constraints in plugins
    * [FORGE-1804] - Generated code is not properly indented
    * [FORGE-1856] - Allow execution of native commands
    * [FORGE-1876] - Addon services should be exposed through @Produces methods 
    * [FORGE-1886] - Scaffolding generates java.lang.Long for Ids
    * [FORGE-1893] - Rename --branch parameter to --ref in addon-install-from-git command
    * [FORGE-1900] - JSON should be the default content type when generating JAXRS Endpoints
    * [FORGE-1906] - Web Root path in Scaffold should be "/" by default in the UI input


** Feature Request
    * [FORGE-1622] - It would be good if Aesh had access to export variables
    * [FORGE-1650] - Support creation of JSON object models from application code through JSON-P APIs
    * [FORGE-1776] - Support the equivalent of git-patch in Forge 2
    * [FORGE-1833] - Provide a JAX-RS Client API implementation 
    * [FORGE-1855] - Simple Container should support singleton services
    * [FORGE-1861] - Having a cp command like in Forge 1.x
    * [FORGE-1863] - Create a GenerateHashcodeEquals command inside the dev-tools-java addon.
    * [FORGE-1866] - WriteableResource should expose the resource output stream
    * [FORGE-1873] - Cannot install Addon from git with branch
    * [FORGE-1879] - Missing a setter in the generated JSF Backing Bean
    * [FORGE-1880] - Being able to add @Named to an EJBs... or any annotation anywhere
    * [FORGE-1883] - Add resolveChildren(String) in Resource interface
    * [FORGE-1887] - Unable to install the Arquillian add-on from Git
    * [FORGE-1894] - AbstractFileResource.getChild() should not throw exceptions when children do not exist
    * [FORGE-1895] - Furnace maven plugin should provide an option to clean the target repository before deploying
    * [FORGE-1916] - Add versioning and exception handling to JAX-RS scaffolding




** Quality Risk
    * [FORGE-1872] - AddonRegistryIncompatibleServiceLookupTest fails when run in JDK 8






** Task
    * [FORGE-1836] - Refactor towards JDK 1.7 enhancements




** Sub-task
    * [FORGE-1398] - Being able to create embeddables
    * [FORGE-1821] - Download links on Forge 2 website should actually work and probably should automatically point to the latest release


