== Forge 2.17.0.Final (Ring) is here!

The Forge Team is proud to announce the immediate availability of JBoss Forge 2.17.0.Final.

Head to the link:http://forge.jboss.org/download[Downloads] page and grab it now!

What's new and noteworthy? 
===========================
* *Support for ZIP files*: We´ve introduced `ZipFileResource` to our list of supported resources. You can now extract files without much fuzz.
* *Auto-Update for Standalone shell*: Updating Forge using the IDE is easy: Just update the plugin. But what about the standalone shell? A new command `forge-update` is introduced to update your local Forge installation automatically to the latest version.
* *Event firing on Facet installation/registration*: Do you want to listen for changes in your project and react to it? You can now listen for Facet installation and registration events and perform any action you like.
* *Component Upgrades*: We've upgraded Furnace and Roaster. Check the release notes below.

Contributors
=============

Many thanks to Matej Briskar who helped to make this release better than ever.

Release Notes - Forge - Version 2.17.0.Final
============================================

++++
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2194'>FORGE-2194</a>] -         Generated JAX-RS endpoing code from entities is wrong for primitive types
</li>
</ul>
            
<h2>        Component  Upgrade
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2366'>FORGE-2366</a>] -         Upgrade to Roaster 2.15.0.Final
</li>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2383'>FORGE-2383</a>] -         Upgrade to Furnace 2.20.0.Final
</li>
</ul>
                
<h2>        Enhancement
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2364'>FORGE-2364</a>] -         Introduce JavaEEFacet.getSpecName()
</li>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2365'>FORGE-2365</a>] -         Support appendable OutputStream in WriteableResource
</li>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2379'>FORGE-2379</a>] -         Introduce UIProvider.getName()
</li>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2384'>FORGE-2384</a>] -         JPAFacet.isInstalled() should only check for descriptor&#39;s existence
</li>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2386'>FORGE-2386</a>] -         Introduce UIProvider.isEmbedded()
</li>
</ul>
        
<h2>        Feature Request
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2283'>FORGE-2283</a>] -         Provide a method for updating the user&#39;s installation automatically.
</li>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2308'>FORGE-2308</a>] -         Create a ZipResource
</li>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2319'>FORGE-2319</a>] -         Fire events on Facets installation
</li>
<li>[<a href='https://issues.jboss.org/browse/FORGE-2378'>FORGE-2378</a>] -         project-new gives error when parent POM inherits groupId from its own parent: [FATAL]  parent.groupId is missing
</li>
</ul>
++++
