:toc:
:toclevels: 4

== How to get your addon listed in the website

. Fork the link:https://github.com/forge/website-data/fork[forge/website-data] repository
. Create a YAML file under *addons/community* named after your addon (_twitter.yaml_) in this example) containing the following addon info:
+
[source,yaml]
----
id: org.george.twitter:twitter
name: Twitter
description: Setup a Twitter account and tweet away!
author: George Gastaldi
email: gegastaldi@gmail.com
website: https://github.com/gastaldi/twitter-addon
repo: https://github.com/gastaldi/twitter-addon.git
ref: master
tags: Twitter
logo: https://abs.twimg.com/a/1403183846/images/oauth_application.png
----

- id: the groupId:artifactId of your addon
- name: the name of your addon
- description: A short description of what your addon is about
- author: the author's name (can be an organization name)
- email: the author's e-mail
- website: (Optional) if there is a website describing this addon or the Github URL if not available
- repo: the git repository (don't forget the .git suffix)
- ref: the branch name where your addon should be fetch (default is master)
- tags: any tags that would allow to find your addon in the search feature in the website
- logo: (Optional) a URL specifying a logo for your addon

. Submit a Pull-request with your changes
.. We'll review it and merge
. Have a beer!

