== Introduction


=== JBoss Forge

It's not so easy to explain what Forge is in a few paragraphs, so we will quote the 
introduction from http://www.amazon.com/Continuous-Enterprise-Development-Andrew-Rubinger/dp/1449328296[Continuous Enterprise Development] (a book):

[quote, Continuous Enterprise Development]
____________________________________________________________________
If you’ve spent any time developing Java EE-based projects (or any nontrivial application,
for that matter!), you’ve likely invested a good amount of energy in creating the
project layout, defining dependencies, and informing the build system of the relevant
class paths to be used in compilation and execution. Although Maven enables us to
reduce that load as compared with undertaking project setup manually, there’s typically
quite a bit of boilerplate involved in the _pom.xml_ defining your requirements.

JBoss Forge offers an incremental project enhancement for Java EE. Implemented as a command shell and integration with some IDE, Forge gives us the ability to alter project files and folders. Some concrete tasks we might use Forge to handle are:

- Adding Java Persistence API (JPA) entities and describing their model
- Configuring Maven dependencies
- Setting up project scaffolding
- Generating a view layer, reverse-engineered from a domain model
- Deploying to an application server

Because Forge is built atop a modular, plug-in-based architecture, it’s extensible to additional
tasks that may be specific to your application.
Overall, the goal of Forge is to ease project setup at all stages of development, so we’ll
be employing it in this guide to speed along the construction of our examples.
____________________________________________________________________

=== What's this lab about?

This hands-on-lab (HoL) should give you a good practical introduction to http://forge.jboss.org[JBoss Forge]. You will first install JBoss Forge, use it and then develop and entire Java EE application and create addons to extend the capabilities of Forge. Forge can either be used within an IDE, or directly in the system terminal via a command line interface (CLI).

The idea is that you leave this hands on lab (HoL) with a good understanding of what JBoss Forge is, what it is not, and how it can help you in your projects. Then, you'll be prepared to investigate a bit more and, hopefully,  http://forge.jboss.org/community[contribute].

NOTE: Get this tutorial from https://github.com/forge/docs/tree/master/tutorials/forge-hol

=== How does this lab work?

You have this material in your hands (either https://github.com/forge/docs/blob/master/tutorials/forge-hol/docs/forge-hol.pdf[electronically] or printed) and you can now follow it step by step or choose any section "à la carte". The structure of this hands on lab is as follow :

- _Installing Forge_ : in this section you will install JBoss Forge, either on a standalone mode, or with JBDS (JBoss Developer Studio)
- _Using Forge_ : in this section you will play with Forge, create a project, add entities, scaffold a JSF web application, REST endpoints, generate some Arquillian tests and deploy them on WildFly
- _Developing Forge_ : in this section you will quickly create a full web application, build forge addons, and use these addons in the application

If you have Forge already installed, skip to the _Using Forge_ section and start using it. If you already know JBoss Forge a bit, jump to the section on _Developing Forge_ and start hacking some addons. This "à la carte" mode allows you to make the most of this 3 hours long hands on lab.

=== What do you have to do?

This lab should be as self explanatory as possible. So your job is to follow the instructions by yourself, do what you are supposed to do, and do not hesitate to ask for any clarification or assistance, that's why the team is here. Make sure you have the required software installed (see below) and be ready to have some fun!

=== Software requirements

The following software needs to be downloaded and installed:

- http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK 8]
- http://maven.apache.org/download.cgi[Maven 3.2.x]
- http://forge.jboss.org/download[JBoss Forge 2.12.2] or higher
- http://wildfly.org/downloads/[WildFly 9.0.x]
