== Using Forge

Forge is a code generator engine and it can be used through multiple UIs such as

- Command Line Interface (CLI)
- JBoss Developer Studio (JBDS)

In this section you will be getting used to Forge by doing small tasks, either with CLI, JBDS, or both. JBoss Forge doesn't create any dependency on your code, it just generates it. So you can switch from CLI, to JBDS, to your own IDE without getting on Forge's way.

But let's get started.

=== Creating a new project

Setting up a new project involves a lot of activities. You basically rely on a build and dependency management framework such as Maven and Gradle. Even if you feel comfortable reading the configuration files, i.e. pom.xml or build.gradle for those, it takes some time to write them from scratch. What you usually do is consulting manuals or textbooks, look in internet or most often - copy and paste them from one of your recent projects. Some of you may decide to use archetypes or IDE wizards, but you will soon realize that these generate too much garbage in your project configurate, that you will usually delete.

==== CLI

The `project-new` is the one we need to quick start a project :

[code, script]
----
project-new --named cdbookstore
----

This will create an empty Maven project structure and a `pom.xml` file. The default `groupId` is `org.cdbookstore`, `artifactId` is `cdbookstore` and version number `1.0.0-SNAPSHOT`. Also, the default project created is a web application, that's why you can see a `packaging` of type `war` and `maven-war-plugin` defined. If you want to change any of these parameters, just press `TAB` after a command and you will get all the parameters :

[code, script]
----
project-new --named cdbookstore --topLevelPackage com.example.project --projectFolder /directory/path --finalName cdbookwebapp --version 1.0.0.Final
----

==== JBDS

=== Setting up persistence and validation

==== CLI

==== JBDS

=== Scaffolding JSF

==== CLI

==== JBDS

=== Scaffolding RESTEndpoints

==== CLI

==== JBDS

=== Deploying on JBoss

==== CLI

==== JBDS

=== Creating Arquillian tests

==== CLI

==== JBDS

=== Scaffolding AngularJS

==== CLI

==== JBDS
