== Using Forge

Forge is a code generator engine and it can be used through multiple UIs such as

- Command Line Interface (CLI)
- JBoss Developer Studio (JBDS)

In this section you will be getting used to Forge by doing small tasks, either with CLI, JBDS, or both. JBoss Forge doesn't create any dependency on your code, it just generates it. So you can switch from CLI, to JBDS, to your own IDE without getting on Forge's way.

But let's get started.

=== Creating a new project

Setting up a new project involves a lot of activities. You basically rely on a build and dependency management framework such as Maven and Gradle. Even if you feel comfortable reading the configuration files, i.e. pom.xml or build.gradle for those, it takes some time to write them from scratch. What you usually do is consulting manuals or textbooks, look in internet or most often - copy and paste them from one of your recent projects. Some of you may decide to use archetypes or IDE wizards, but you will soon realize that these generate too much garbage in your project configurate, that you will usually delete.

==== CLI

The `project-new` is the one we need to quick start a project :

[code, script]
----
$ project-new --named cdbookstore
----

This will create an empty Maven project structure and a `pom.xml` file. The default `groupId` is `org.cdbookstore`, `artifactId` is `cdbookstore` and version number `1.0.0-SNAPSHOT`. Also, the default project created is a web application, that's why you can see a `packaging` of type `war` and `maven-war-plugin` defined. If you want to change any of these parameters, just press `TAB` after a command and you will get all the parameters :

[code, script]
----
$ project-new --named cdbookstore --topLevelPackage com.example.project --projectFolder /directory/path --finalName cdbookwebapp --version 1.0.0.Final
----

==== JBDS

=== Setting up persistence and validation

Most of the Java EE applications need a relational database, map entities to it and do some sort of validation. Again, with JBoss Forge it is very easy to setup the persistence configuration, create an entity (or an embeddable), add fields to it and Bean Validation constraints. 

==== CLI

To create a new JPA entity, let's use the `jpa-new-entity` command : 

[code, script]
----
[cdbookstore]$ jpa-new-entity --named Book
----

This command has several effects. First of all, it has created a `persistence.xml` file in the right place (under the `META-INF` directory) with all the default configuration for Hibernate. Then, it has created a `Book` entity under the subpackage `model`. Notice that this entity already has an `id` and `version` with its getters/setters. As you can see, the good thing with Forge is that with only one command all is setup and ready to go. 

If you do not wish to use the Java EE container default data-source, you can also specify additional connection parameters such as JNDI data-source names, JDBC connection information, and data-source types. Note, however, that this means you will probably need configure your application server to provide this new data-source and/or database connection.

[code, script]
----
[cdbookstore]$ jpa-setup --provider Eclipse Link --dbType POSTGRES --dataSourceName java:comp/DefaultDataSource
----

Then, let's create a few fields. Again, one single command end Forge will do its best to simplify our lives :

[code, script]
----
[Book.java]$ jpa-new-field --named title
----

This creates an attribute called `title` of type `String` with get/set methods. Notice that Forge has also updated the `toString` method. Let's add more commands with different parameters (remember to press `TAB` to get the parameters) :

[code, script]
----
[Book.java]$ jpa-new-field --named description --length 2000
[Book.java]$ jpa-new-field --named price --type java.lang.Float
[Book.java]$ jpa-new-field --named nbOfPages --type java.lang.Integer
[Book.java]$ jpa-new-field --named publicationDate --typeName java.util.Date --temporalType DATE
----

As you can see, Forge has a all set of parameters to quickly create attributes and customize their JPA mapping. Now let's say we want to specify that a book is written in a certain language. We can use Forge to quickly create a Java enum and then have it as a JPA Enumerated in the `Book` entity :

[code, script]
----
[Book.java]$ java-new-enum --named Language --targetPackage org.cdbookstore.model
[Language.java]$ java-new-enum-const ENGLISH
[Language.java]$ java-new-enum-const FRENCH
----

This creates a Java enum, but notice the path on the left side : Forge CLI was set on the `Book` class (that's why you could read `[Book.java]$`). When we created the enum, the path changed to `[Language.java]$`. Like any other shell script, Forge has a certain number of commands to navigate between directories, classes or files (you will find the full list of commands in the Appendix). So, to go back to the `Book` entity we just use the `cd` command :

[code, script]
----
[Language.java]$ cd ..
[model]$ cd Book.java
[Book.java]$
----

Now that we are in the `Book` entity, we can create a new enum field with the following command : 

[code, script]
----
[Book.java]$ jpa-new-field --named language --type org.cdbookstore.model.Language
----

By default a JPA field is of type `String`. With the `--type` parameter we can choose from basic datatypes (`int`, `byte`, `char`…), enum, or from other entities and choosing your cardinality (One-to-One, One-to-Many, Many-to-One, Many-to-Many). So let's create a new `Author` entity and have a Many-to-One relationship with `Book` :

[code, script]
----
Book.java]$ jpa-new-entity --named Author
[Author.java]$ jpa-new-field --named firstName
[Author.java]$ cd ../Book.java
[Book.java]$ jpa-new-field --named author --type org.cdbookstore.model.Author --relationshipType Many-to-One
----

Forge takes care of all the JPA relational mapping between both entities. Now, on an entity, we can add Bean Validation constraints on properties with the `constraint-add` command.

[code, script]
----
[Book.java]$ constraint-add --constraint NotNull --onProperty title
[Book.java]$ constraint-add --constraint Past --onProperty publicationDate
[Book.java]$ constraint-add --onProperty description --constraint Size --max 3000
----

Behind the scenes Forge as created a `validation.xml` file, added the Bean Validation dependency and the needed constraints. BTW if you want to have a quick look at your code, you can use the `more` command or even `ls` your class :

[code, script]
----
[Book.java]$ ls

[fields]
author::org.cdbookstore.model.Author      language::org.cdbookstore.model.Language  publicationDate::java.lang.String
description::java.lang.String             nbOfPages::java.lang.Integer              title::java.lang.String
id::java.lang.Long                        price::java.lang.Float                    version::int

[methods]
equals(java.lang.Object)::boolean                  getPublicationDate()::java.lang.String             setLanguage(org.cdbookstore.model.Language)::void
getAuthor()::org.cdbookstore.model.Author          getTitle()::java.lang.String                       setNbOfPages(java.lang.Integer)::void
getDescription()::java.lang.String                 getVersion()::int                                  setPrice(java.lang.Float)::void
getId()::java.lang.Long                            hashCode()::int                                    setPublicationDate(java.lang.String)::void
getLanguage()::org.cdbookstore.model.Language      setAuthor(org.cdbookstore.model.Author)::void      setTitle(java.lang.String)::void
getNbOfPages()::java.lang.Integer                  setDescription(java.lang.String)::void             setVersion(int)::void
getPrice()::java.lang.Float                        setId(java.lang.Long)::void                        toString()::java.lang.String
----


==== JBDS

=== Scaffolding JSF

JSF is the default Java EE user interface framework, and so, JBoss Forge has a great support for it. In fact, Forge can scaffold an entire CRUD web application very easily. The JSF generated application follows several patterns and best practices : usage of CDI conversation, extended persistence context, JSF converters and so on. If you don't believe it, just try it. 

==== CLI

Now that we have created fields in the entities, it’s time to scaffold web pages for these entities. We can either scaffold per entity, or use a wildcard to let Forge know it can generate a UI for each entity

[code, script]
----
[model]$ scaffold-generate --targets org.cdbookstore.model.*
----

This has the same effect of scaffolding per entity :

[code, script]
----
[model]$ scaffold-generate --targets org.cdbookstore.model.Book
[model]$ scaffold-generate --targets org.cdbookstore.model.Author
----

By default Forge scaffolds a web application with JSF 2.0 but you can change this configuration by executing the `faces-setup` command. In fact, most of the Forge commands can be setup (e.g. `jpa-setup`, `servlet-setup`...)

[code, script]
----
$ faces-setup --facesVersion 2.2
----

==== JBDS

=== Scaffolding RESTEndpoints

REST is a very popular technology nowadays. If you want to create REST endpoints on our entities, or if you want to add a REST endpoint on your existing Java EE web application, Forge is there to help. Forge can quickly scaffold REST endpoints for each entity, giving you a set of CRUD methods. And again, generating all the code plumbing and following best practices. 

==== CLI

Now that we have a few entities (`Book` and `Author`), it’s time to generate REST endpoints. Like for JSF, it is just a matter of executing one single command :

[code, script]
----
[model]$ rest-generate-endpoints-from-entities --targets org.cdbookstore.model.*
----

This is the easiest command to generate the REST endpoints, but like most Forge commands, you can customize a few paramaters if you want, such as package name and so on.

While "holding" most files, you may inspect them using ls. This also works on REST endpoints. So, if you `cd` `BookEndpoint.java` and execute the command `ls`, this is what you get :

[code, script]
----
[BookEndpoint.java]$ ls

[fields]
em::javax.persistence.EntityManager

[methods]
create(org.cdbookstore.model.Book)::javax.ws.rs.core.Response  findById(java.lang.Long)::javax.ws.rs.core.Response            update(org.cdbookstore.model.Book)::javax.ws.rs.core.Response
deleteById(java.lang.Long)::javax.ws.rs.core.Response          listAll(java.lang.Integer,java.lang.Integer)::java.util.List
----

==== JBDS

=== Deploying on JBoss

==== CLI

==== JBDS

=== Creating Arquillian tests

==== CLI

==== JBDS

=== Scaffolding AngularJS

==== CLI

==== JBDS
