== Introduction


=== JBoss Forge

It's not so easy to explain what Forge is in a few paragraphs. 
That is why we will re-use the introduction from http://www.amazon.com/Continuous-Enterprise-Development-Andrew-Rubinger/dp/1449328296[Continuous Enterprise Development] book:

If you’ve spent any time developing Java EE–based projects (or any nontrivial application,
for that matter!), you’ve likely invested a good amount of energy in creating the
project layout, defining dependencies, and informing the build system of the relevant
class paths to be used in compilation and execution. Although Maven enables us to
reduce that load as compared with undertaking project setup manually, there’s typically
quite a bit of boilerplate involved in the pom.xml defining your requirements.

JBoss Forge offers “incremental project enhancement for Java EE.” Implemented as a
command shell and integration with some IDE, Forge gives us the ability to alter project files and folders. 

- Some concrete tasks we might use Forge to handle are:
  * Adding Java Persistence API (JPA) entities and describing their model
  * Configuring Maven dependencies
  * Setting up project scaffolding
  * Generating a view layer, reverse-engineered from a domain model
  * Deploying to an application server

Because Forge is built atop a modular, plug-in-based architecture, it’s extensible to additional
tasks that may be specific to your application.
Overall, the goal of Forge is to ease project setup at all stages of development, so we’ll
be employing it in this text to speed along the construction of our examples.

=== What's this HoL about?

This hands-on lab (HoL) give you a good practical introduction to JBoss Forge. You will first install JBoss Forge, use it and then create addons to extend the capabilities of Forge. Forge can either by used with an IDE, or directly with a command line interface (CLI). 

The idea is that you leave this hands on lab (HoL) with a good understanding of what JBoss is, what it is not, and how it can help you in your projects. Then, you'll have your entire time to investigate a big more and, hopefully,  http://forge.jboss.org/community[contribute] ;o)

=== How does this HoL work?

You have this material in your hands (either https://github.com/forge/docs/blob/master/tutorials/forge-hol/forge-hol.pdf[electronically] or printed) and you can now follow it step by step or choose any section "à la carte". The structure of this hands on lab is as follow :

- Installing Forge : in this section you will install JBoss Forge, either on a standalone mode, or with JBDS (JBoss Developer Studio)
- Using Forge : in this section you will play with Forge, create a project, add entities, scaffold a JSF and AngularJS web application, generate some Arquillian tests and deploy it on WildFly
- Developing Forge : in this section you will quickly create a full web application, build extensions, and add these extensions to the application

If Forge is already installed, just go to the "Using Forge" section ans tart using it. If you already know JBoss Forge a bit, jump to the section on "Developing Forge" and start hacking some addons. This "à la carte" mode allows you to make the most of this 3 hours long hands on lab.

=== What do you have to do?

=== Software requirements

The following software needs to be downloaded and installed:

- JDK 7 from http://www.oracle.com/technetwork/java/javase/downloads/index.html
- Maven 3.2.x from http://maven.apache.org/download.cgi
- JBoss Forge 2.12.x from http://forge.jboss.org/download
- WildFly 8.1 from http://wildfly.org/downloads/
